// Mock data for stocks
export const stocks = [
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    price: 182.52,
    change: 1.25,
    sector: "Technology",
    industry: "Consumer Electronics",
    description:
      "Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, Mac, iPad, and wearables, home, and accessories.",
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corporation",
    price: 337.22,
    change: 0.87,
    sector: "Technology",
    industry: "Software",
    description:
      "Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide. The company operates through three segments: Productivity and Business Processes, Intelligent Cloud, and More Personal Computing.",
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    price: 131.86,
    change: -0.45,
    sector: "Technology",
    industry: "Internet Content & Information",
    description:
      "Alphabet Inc. provides various products and platforms in the United States, Europe, the Middle East, Africa, the Asia-Pacific, Canada, and Latin America. It operates through Google Services, Google Cloud, and Other Bets segments.",
  },
  {
    symbol: "AMZN",
    name: "Amazon.com, Inc.",
    price: 127.74,
    change: 2.13,
    sector: "Consumer Cyclical",
    industry: "Internet Retail",
    description:
      "Amazon.com, Inc. engages in the retail sale of consumer products and subscriptions through online and physical stores in North America and internationally. It operates through three segments: North America, International, and Amazon Web Services (AWS).",
  },
  {
    symbol: "TSLA",
    name: "Tesla, Inc.",
    price: 248.48,
    change: -1.78,
    sector: "Consumer Cyclical",
    industry: "Auto Manufacturers",
    description:
      "Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems in the United States, China, and internationally. The company operates in two segments, Automotive, and Energy Generation and Storage.",
  },
  {
    symbol: "META",
    name: "Meta Platforms, Inc.",
    price: 302.55,
    change: 1.45,
    sector: "Technology",
    industry: "Internet Content & Information",
    description:
      "Meta Platforms, Inc. develops products that enable people to connect and share with friends and family through mobile devices, personal computers, virtual reality headsets, and wearables worldwide. It operates in two segments, Family of Apps and Reality Labs.",
  },
  {
    symbol: "NFLX",
    name: "Netflix, Inc.",
    price: 401.78,
    change: 0.92,
    sector: "Communication Services",
    industry: "Entertainment",
    description:
      "Netflix, Inc. provides entertainment services. It offers TV series, documentaries, feature films, and mobile games across various genres and languages. The company provides members the ability to receive streaming content through a host of internet-connected devices.",
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase & Co.",
    price: 142.45,
    change: -0.32,
    sector: "Financial Services",
    industry: "Banks",
    description:
      "JPMorgan Chase & Co. operates as a financial services company worldwide. It operates through four segments: Consumer & Community Banking, Corporate & Investment Bank, Commercial Banking, and Asset & Wealth Management.",
  },
];

// Helper function to get a stock by symbol
export function getStockBySymbol(symbol: string) {
  return stocks.find((stock) => stock.symbol === symbol);
}

// Mock data for financial ratios
export function getStockRatios(symbol: string) {
  // Different ratios for different stocks
  const baseRatios = [
    {
      id: "pe",
      name: "P/E Ratio",
      value: symbol === "AAPL" ? 28.5 : symbol === "MSFT" ? 32.1 : 25.7,
      change: symbol === "AAPL" ? 2.3 : symbol === "MSFT" ? -1.5 : 0.8,
      industry: 26.4,
      explanation:
        "The Price-to-Earnings ratio shows how much investors are willing to pay for each dollar of earnings. This company's P/E is slightly higher than the industry average, suggesting investors expect stronger future growth.",
    },
    {
      id: "pb",
      name: "P/B Ratio",
      value: symbol === "AAPL" ? 15.2 : symbol === "MSFT" ? 12.8 : 9.5,
      change: symbol === "AAPL" ? 1.8 : symbol === "MSFT" ? 0.9 : -0.7,
      industry: 10.2,
      explanation:
        "The Price-to-Book ratio compares a company's market value to its book value. This higher-than-average P/B suggests the market values the company's assets more than what's recorded on the balance sheet.",
    },
    {
      id: "roe",
      name: "ROE",
      value: symbol === "AAPL" ? 42.5 : symbol === "MSFT" ? 38.2 : 29.7,
      change: symbol === "AAPL" ? 3.2 : symbol === "MSFT" ? 1.5 : -2.1,
      industry: 31.5,
      explanation:
        "Return on Equity measures how efficiently a company uses its equity to generate profits. This company's strong ROE indicates effective management and good profitability relative to shareholder investment.",
    },
    {
      id: "de",
      name: "Debt-to-Equity",
      value: symbol === "AAPL" ? 1.25 : symbol === "MSFT" ? 0.45 : 0.78,
      change: symbol === "AAPL" ? -0.15 : symbol === "MSFT" ? 0.05 : -0.03,
      industry: 0.85,
      explanation:
        "The Debt-to-Equity ratio shows how much debt a company is using to finance its assets relative to shareholder equity. This ratio indicates a moderate level of financial leverage, which can amplify returns but also increases financial risk.",
    },
    {
      id: "cr",
      name: "Current Ratio",
      value: symbol === "AAPL" ? 1.35 : symbol === "MSFT" ? 1.85 : 1.62,
      change: symbol === "AAPL" ? 0.08 : symbol === "MSFT" ? -0.12 : 0.05,
      industry: 1.5,
      explanation:
        "The Current Ratio measures a company's ability to pay short-term obligations. This ratio suggests the company has adequate liquidity to cover its short-term liabilities, indicating good short-term financial health.",
    },
    {
      id: "gm",
      name: "Gross Margin",
      value: symbol === "AAPL" ? 43.2 : symbol === "MSFT" ? 68.5 : 55.1,
      change: symbol === "AAPL" ? 1.2 : symbol === "MSFT" ? 0.7 : -0.9,
      industry: 52.3,
      explanation:
        "Gross Margin represents the percentage of revenue that exceeds the cost of goods sold. This company's gross margin indicates strong pricing power and efficient production costs compared to competitors.",
    },
    {
      id: "npm",
      name: "Net Profit Margin",
      value: symbol === "AAPL" ? 21.5 : symbol === "MSFT" ? 33.2 : 18.7,
      change: symbol === "AAPL" ? 0.8 : symbol === "MSFT" ? 1.5 : -0.6,
      industry: 19.8,
      explanation:
        "Net Profit Margin measures how much net income is generated as a percentage of revenue. This above-industry margin demonstrates the company's strong ability to convert revenue into actual profit.",
    },
    {
      id: "eps",
      name: "EPS Growth",
      value: symbol === "AAPL" ? 12.5 : symbol === "MSFT" ? 15.8 : 9.2,
      change: symbol === "AAPL" ? 2.3 : symbol === "MSFT" ? 1.1 : -0.7,
      industry: 10.5,
      explanation:
        "Earnings Per Share Growth shows the percentage increase in earnings per share over time. This company's strong EPS growth indicates improving profitability and potential for future stock price appreciation.",
    },
    {
      id: "dy",
      name: "Dividend Yield",
      value: symbol === "AAPL" ? 0.58 : symbol === "MSFT" ? 0.82 : 1.25,
      change: symbol === "AAPL" ? -0.05 : symbol === "MSFT" ? 0.03 : 0.12,
      industry: 1.05,
      explanation:
        "Dividend Yield shows how much a company pays out in dividends each year relative to its stock price. This company's yield is below the industry average, suggesting it may be reinvesting more profits for growth rather than distributing them to shareholders.",
    },
  ];

  return baseRatios;
}

export const yFinanceRes = {
  address1: "One Microsoft Way",
  city: "Redmond",
  state: "WA",
  zip: "98052-6399",
  country: "United States",
  phone: "425 882 8080",
  website: "https://www.microsoft.com",
  industry: "Software - Infrastructure",
  industryKey: "software-infrastructure",
  industryDisp: "Software - Infrastructure",
  sector: "Technology",
  sectorKey: "technology",
  sectorDisp: "Technology",
  longBusinessSummary: "",
  fullTimeEmployees: 228000,
  companyOfficers: [
    {
      maxAge: 1,
      name: "Mr. Satya  Nadella",
      age: 57,
      title: "Chairman & CEO",
      yearBorn: 1967,
      fiscalYear: 2024,
      totalPay: 7869791,
      exercisedValue: 0,
      unexercisedValue: 0,
    },
  ],
  overallRisk: 3,
  irWebsite: "http://www.microsoft.com/investor/default.aspx",
  executiveTeam: [],
  priceHint: 2,
  previousClose: 458.87,
  open: 455.59,
  dayLow: 454.3201,
  dayHigh: 458.34,
  regularMarketPreviousClose: 458.87,
  regularMarketOpen: 455.59,
  regularMarketDayLow: 454.3201,
  regularMarketDayHigh: 458.34,
  dividendRate: 3.32,
  dividendYield: 0.72,
  exDividendDate: 1747267200,
  payoutRatio: 0.2442,
  fiveYearAvgDividendYield: 0.84,
  beta: 0.985,
  trailingPE: 35.462074,
  forwardPE: 30.646824,
  volume: 15422952,
  regularMarketVolume: 15422952,
  averageVolume: 24920950,
  averageVolume10days: 21106480,
  averageDailyVolume10Day: 21106480,
  bid: 432.43,
  ask: 459.49,
  bidSize: 1,
  askSize: 5,
  marketCap: 3405366951936,
  fiftyTwoWeekLow: 344.79,
  fiftyTwoWeekHigh: 468.35,
  priceToSalesTrailing12Months: 12.612002,
  fiftyDayAverage: 399.0244,
  twoHundredDayAverage: 415.12674,
  trailingAnnualDividendRate: 3.24,
  trailingAnnualDividendYield: 0.0070608235,
  currency: "USD",
  tradeable: false,
  enterpriseValue: 3430769491968,
  profitMargins: 0.35789,
  floatShares: 7421915327,
  sharesOutstanding: 7432540160,
  sharesShort: 50313676,
  shortRatio: 1.85,
  shortPercentOfFloat: 0.0068,
  impliedSharesOutstanding: 7432540160,
  bookValue: 43.3,
  priceToBook: 10.581294,
  mostRecentQuarter: 1743379200,
  earningsQuarterlyGrowth: 0.177,
  netIncomeToCommon: 96635002880,
  trailingEps: 12.92,
  forwardEps: 14.95,
  lastSplitFactor: "2:1",
  lastSplitDate: 1045526400,
  enterpriseToRevenue: 12.706,
  enterpriseToEbitda: 22.999,
  lastDividendValue: 0.83,
  lastDividendDate: 1747267200,
  quoteType: "EQUITY",
  currentPrice: 458.17,
  targetHighPrice: 650.0,
  targetLowPrice: 429.86,
  targetMeanPrice: 508.66693,
  targetMedianPrice: 500.0,
  recommendationMean: 1.41667,
  recommendationKey: "strong_buy",
  numberOfAnalystOpinions: 52,
  totalCash: 79617998848,
  totalCashPerShare: 10.712,
  ebitda: 149172994048,
  totalDebt: 105018998784,
  quickRatio: 1.244,
  currentRatio: 1.372,
  totalRevenue: 270010007552,
  debtToEquity: 32.626,
  revenuePerShare: 36.325,
  returnOnAssets: 0.14581999,
  returnOnEquity: 0.3361,
  grossProfits: 186509000704,
  freeCashflow: 54817001472,
  operatingCashflow: 130710003712,
  earningsGrowth: 0.177,
  revenueGrowth: 0.133,
  grossMargins: 0.69074994,
  ebitdaMargins: 0.55247,
  operatingMargins: 0.45671,
  financialCurrency: "USD",
  symbol: "MSFT",
  language: "en-US",
  region: "US",
  typeDisp: "Equity",
  quoteSourceName: "Nasdaq Real Time Price",
  dividendDate: 1749686400,
  earningsTimestamp: 1746043200,
  epsTrailingTwelveMonths: 12.92,
  epsForward: 14.95,
  epsCurrentYear: 13.38589,
  priceEpsCurrentYear: 34.227833,
  averageAnalystRating: "1.4 - Strong Buy",
  cryptoTradeable: false,
  regularMarketChangePercent: -0.15254466,
  regularMarketPrice: 458.17,
  marketState: "PRE",
  shortName: "Microsoft Corporation",
  longName: "Microsoft Corporation",
  preMarketTime: 1747828012,
  regularMarketTime: 1747771201,
  exchange: "NMS",
  messageBoardId: "finmb_21835",
  exchangeTimezoneName: "America/New_York",
  exchangeTimezoneShortName: "EDT",
  gmtOffSetMilliseconds: -14400000,
  market: "us_market",
  preMarketChange: -1.8700256,
  preMarketChangePercent: -0.40815103,
  preMarketPrice: 456.3,
  regularMarketChange: -0.6999817,
  regularMarketDayRange: "454.3201 - 458.34",
  fullExchangeName: "NasdaqGS",
  averageDailyVolume3Month: 24920950,
  fiftyTwoWeekLowChange: 113.380005,
  displayName: "Microsoft",
  trailingPegRatio: 2.1504,
};
