export const sampleStocks = [
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    exch: "NMS",
    type: "S",
    exchDisp: "NASDAQ",
    typeDisp: "Equity",
  },
  {
    symbol: "APLY",
    name: "YieldMax AAPL Option Income Strategy ETF",
    exch: "PCX",
    type: "E",
    exchDisp: "NYSEArca",
    typeDisp: "ETF",
  },
  {
    symbol: "AAPU",
    name: "Direxion Daily AAPL Bull 1.5X Shares",
    exch: "NGM",
    type: "E",
    exchDisp: "NASDAQ",
    typeDisp: "ETF",
  },
  {
    symbol: "AAPD",
    name: "Direxion Daily AAPL Bear 1X Shares",
    exch: "NGM",
    type: "E",
    exchDisp: "NASDAQ",
    typeDisp: "ETF",
  },
  {
    symbol: "AAPLEXX",
    name: "AAPLEXX",
    exch: "NAS",
    type: "M",
    exchDisp: "NASDAQ",
    typeDisp: "Fund",
  },
  {
    symbol: "AAPB",
    name: "GraniteShares 2x Long AAPL Daily ETF",
    exch: "NGM",
    type: "E",
    exchDisp: "NASDAQ",
    typeDisp: "ETF",
  },
  {
    symbol: "AAPLLXX",
    name: "AAPLLXX",
    exch: "NAS",
    type: "M",
    exchDisp: "NASDAQ",
    typeDisp: "Fund",
  },
  {
    symbol: "AAPLKXX",
    name: "AAPLKXX",
    exch: "NAS",
    type: "M",
    exchDisp: "NASDAQ",
    typeDisp: "Fund",
  },
  {
    symbol: "AAPLXXX",
    name: "AAPLXXX",
    exch: "NAS",
    type: "M",
    exchDisp: "NASDAQ",
    typeDisp: "Fund",
  },
];

export const recommendedStocks = [
  {
    ticker: "WMT",
    name: "Walmart Inc.",
  },
  {
    ticker: "AAPL",
    name: "Apple Inc.",
  },
  {
    ticker: "TSLA",
    name: "Tesla, Inc.",
  },
  {
    ticker: "NVDA",
    name: "NVIDIA Corporation",
  },
  {
    ticker: "META",
    name: "Meta Platforms, Inc.",
  },
  {
    ticker: "GOOGL",
    name: "Alphabet Inc.",
  },
  {
    ticker: "AMZN",
    name: "Amazon.com, Inc.",
  },
];

export const ratiosTypes = [
  {
    label: "P/E",
    key: "trailingPE",
    description:
      "The Price-to-Earnings ratio shows how much investors are willing to pay for each dollar of earnings. This company's P/E is slightly higher than the industry average, suggesting investors expect stronger future growth.",
  },
  {
    label: "P/B",
    key: "priceToBook",
    description:
      "The Price-to-Book ratio compares a company's market value to its book value. This higher-than-average P/B suggests the market values the company's assets more than what's recorded on the balance sheet.",
  },
  {
    label: "EPS",
    key: "trailingEps",
    description:
      "Earnings Per Share Growth shows the percentage increase in earnings per share over time. This company's strong EPS growth indicates improving profitability and potential for future stock price appreciation.",
  },
  {
    label: "ROE",
    key: "returnOnEquity",
    description:
      "Return on Equity measures how efficiently a company uses its equity to generate profits. This company's strong ROE indicates effective management and good profitability relative to shareholder investment.",
  },
  { label: "PEG", key: "trailingPegRatio" },
  {
    label: "Dividend yield",
    key: "dividendYield",
    description:
      "Dividend Yield shows how much a company pays out in dividends each year relative to its stock price. This company's yield is below the industry average, suggesting it may be reinvesting more profits for growth rather than distributing them to shareholders.",
  },
  {
    label: "Debt-to-Equity",
    key: "debtToEquity",
    description:
      "The Debt-to-Equity ratio shows how much debt a company is using to finance its assets relative to shareholder equity. This ratio indicates a moderate level of financial leverage, which can amplify returns but also increases financial risk.",
  },
  { label: "Quick Ratio", key: "quickRatio" },
  {
    label: "Current Ratio",
    key: "currentRatio",
    description:
      "The Current Ratio measures a company's ability to pay short-term obligations. This ratio suggests the company has adequate liquidity to cover its short-term liabilities, indicating good short-term financial health.",
  },
  {
    label: "Gross Margin",
    key: "grossMargins",
    description:
      "Gross Margin represents the percentage of revenue that exceeds the cost of goods sold. This company's gross margin indicates strong pricing power and efficient production costs compared to competitors.",
  },
  {
    label: "Profit Margin",
    key: "profitMargins",
    description:
      "Net Profit Margin measures how much net income is generated as a percentage of revenue. This above-industry margin demonstrates the company's strong ability to convert revenue into actual profit.",
  },
];

const generalStockStats = [
  { label: "Company name", key: "displayName" },
  { label: "Symbol", key: "symbol" },
  { label: "Market", key: "marketCap" },
  { label: "Price", key: "currentPrice" },
  ...ratiosTypes,
];

const res = {
  address1: "One Microsoft Way",
  city: "Redmond",
  state: "WA",
  zip: "98052-6399",
  country: "United States",
  phone: "425 882 8080",
  website: "https://www.microsoft.com",
  industry: "Software - Infrastructure",
  industryKey: "software-infrastructure",
  industryDisp: "Software - Infrastructure",
  sector: "Technology",
  sectorKey: "technology",
  sectorDisp: "Technology",
  longBusinessSummary: "",
  fullTimeEmployees: 228000,
  companyOfficers: [
    {
      maxAge: 1,
      name: "Mr. Satya  Nadella",
      age: 57,
      title: "Chairman & CEO",
      yearBorn: 1967,
      fiscalYear: 2024,
      totalPay: 7869791,
      exercisedValue: 0,
      unexercisedValue: 0,
    },
  ],
  overallRisk: 3,
  irWebsite: "http://www.microsoft.com/investor/default.aspx",
  executiveTeam: [],
  priceHint: 2,
  previousClose: 458.87,
  open: 455.59,
  dayLow: 454.3201,
  dayHigh: 458.34,
  regularMarketPreviousClose: 458.87,
  regularMarketOpen: 455.59,
  regularMarketDayLow: 454.3201,
  regularMarketDayHigh: 458.34,
  dividendRate: 3.32,
  dividendYield: 0.72,
  exDividendDate: 1747267200,
  payoutRatio: 0.2442,
  fiveYearAvgDividendYield: 0.84,
  beta: 0.985,
  trailingPE: 35.462074,
  forwardPE: 30.646824,
  volume: 15422952,
  regularMarketVolume: 15422952,
  averageVolume: 24920950,
  averageVolume10days: 21106480,
  averageDailyVolume10Day: 21106480,
  bid: 432.43,
  ask: 459.49,
  bidSize: 1,
  askSize: 5,
  marketCap: 3405366951936,
  fiftyTwoWeekLow: 344.79,
  fiftyTwoWeekHigh: 468.35,
  priceToSalesTrailing12Months: 12.612002,
  fiftyDayAverage: 399.0244,
  twoHundredDayAverage: 415.12674,
  trailingAnnualDividendRate: 3.24,
  trailingAnnualDividendYield: 0.0070608235,
  currency: "USD",
  tradeable: false,
  enterpriseValue: 3430769491968,
  profitMargins: 0.35789,
  floatShares: 7421915327,
  sharesOutstanding: 7432540160,
  sharesShort: 50313676,
  shortRatio: 1.85,
  shortPercentOfFloat: 0.0068,
  impliedSharesOutstanding: 7432540160,
  bookValue: 43.3,
  priceToBook: 10.581294,
  mostRecentQuarter: 1743379200,
  earningsQuarterlyGrowth: 0.177,
  netIncomeToCommon: 96635002880,
  trailingEps: 12.92,
  forwardEps: 14.95,
  lastSplitFactor: "2:1",
  lastSplitDate: 1045526400,
  enterpriseToRevenue: 12.706,
  enterpriseToEbitda: 22.999,
  lastDividendValue: 0.83,
  lastDividendDate: 1747267200,
  quoteType: "EQUITY",
  currentPrice: 458.17,
  targetHighPrice: 650.0,
  targetLowPrice: 429.86,
  targetMeanPrice: 508.66693,
  targetMedianPrice: 500.0,
  recommendationMean: 1.41667,
  recommendationKey: "strong_buy",
  numberOfAnalystOpinions: 52,
  totalCash: 79617998848,
  totalCashPerShare: 10.712,
  ebitda: 149172994048,
  totalDebt: 105018998784,
  quickRatio: 1.244,
  currentRatio: 1.372,
  totalRevenue: 270010007552,
  debtToEquity: 32.626,
  revenuePerShare: 36.325,
  returnOnAssets: 0.14581999,
  returnOnEquity: 0.3361,
  grossProfits: 186509000704,
  freeCashflow: 54817001472,
  operatingCashflow: 130710003712,
  earningsGrowth: 0.177,
  revenueGrowth: 0.133,
  grossMargins: 0.69074994,
  ebitdaMargins: 0.55247,
  operatingMargins: 0.45671,
  financialCurrency: "USD",
  symbol: "MSFT",
  language: "en-US",
  region: "US",
  typeDisp: "Equity",
  quoteSourceName: "Nasdaq Real Time Price",
  dividendDate: 1749686400,
  earningsTimestamp: 1746043200,
  epsTrailingTwelveMonths: 12.92,
  epsForward: 14.95,
  epsCurrentYear: 13.38589,
  priceEpsCurrentYear: 34.227833,
  averageAnalystRating: "1.4 - Strong Buy",
  cryptoTradeable: false,
  regularMarketChangePercent: -0.15254466,
  regularMarketPrice: 458.17,
  marketState: "PRE",
  shortName: "Microsoft Corporation",
  longName: "Microsoft Corporation",
  preMarketTime: 1747828012,
  regularMarketTime: 1747771201,
  exchange: "NMS",
  messageBoardId: "finmb_21835",
  exchangeTimezoneName: "America/New_York",
  exchangeTimezoneShortName: "EDT",
  gmtOffSetMilliseconds: -14400000,
  market: "us_market",
  preMarketChange: -1.8700256,
  preMarketChangePercent: -0.40815103,
  preMarketPrice: 456.3,
  regularMarketChange: -0.6999817,
  regularMarketDayRange: "454.3201 - 458.34",
  fullExchangeName: "NasdaqGS",
  averageDailyVolume3Month: 24920950,
  fiftyTwoWeekLowChange: 113.380005,
  displayName: "Microsoft",
  trailingPegRatio: 2.1504,
};
